### ISSUE TITLE
Add resource links for new developers to main page

### ISSUE THREAD

**Issue by compscirunner** [hackerhoursboise/hackerhoursboise.github.io#3]
things like code academy ...

**Comment by msjohncox** [comment]
Thanks! I am trying to push my changes to the development branch and I keep getting that error message: I need to pull down changes first. I think if I do that, it will turn out like the last time and I will lose all my changes. I have a backup now, but really, there has to be a better way.

**Comment by hIGH-aND-mIGHTY** [comment]
This is. It's called stashing

With the branch that has your current changes checked out open the console
in source tree and type "git stash" Then "git pull" to get the current
changes followed by "git stash apply" . Then attempt to commit and push and
such
